### PR TITLE
v0.2.36 3163

### PR DESCRIPTION
**Pull request by sandrew**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@thutterer is your reviewer :dancers: check https://trello.com/c/wuuOTWh4/3163-cnt-review-pr-263 
@thutterer: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/SCC-Connect-Prophet/87127/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 05ac35e0f259bd1b13ae7cac35793191a6c9004c into b88a407a24f6cade78628f15f917611306adfbd7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/87133/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 05ac35e0f259bd1b13ae7cac35793191a6c9004c into b88a407a24f6cade78628f15f917611306adfbd7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/SCC-Connect-Prophet/87585/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 6be5424bbda9c1bbc4c0f26328d302b710054d0b into b88a407a24f6cade78628f15f917611306adfbd7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/87596/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 6be5424bbda9c1bbc4c0f26328d302b710054d0b into b88a407a24f6cade78628f15f917611306adfbd7 )

**Comment by thutterer** [comment]
LGTM

**Pull request merged**
