### PR TITLE
Point to the new API documentation

### PR DESCRIPTION
**Pull request by fschueller**

### CODE REVIEW

**Comment by lagartoflojo** [comment]
This is so cool :+1:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/142834/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f1917f6215603a7a943994b5055298192e0a627e into 04f051051aa545dcc713b1659aa99079efaa91ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/143032/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f1917f6215603a7a943994b5055298192e0a627e into 56d00f8f9bac5aab6a3064ad14f7858873da7b4c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/143075/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged dc17782b49242334b5c8060ccd9386c8562b8742 into 56d00f8f9bac5aab6a3064ad14f7858873da7b4c)

**Pull request merged**
