### PR TITLE
[Review] Request from 'digitaltom' @ 'SUSE/connect/review_160125_re_add_suseconnect_binary_to_usr_sbin_bnc_963080_' 3008

### PR DESCRIPTION
**Pull request by digitaltom**
Please review the following changes:
  * cb04bb3 osc changes
  * c0e21e1 use --match-exact (bnc#952804)
  * 9346c79 use \e[0m to terminate bold font, works better with xterm
  * a23466f add update repos with refresh=true
  * 3eaf338 make SUSEConnect binary available at /usr/sbin/
  * 8f7ec17 v0.2.33

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@wstephenson is your reviewer :dancers: check https://trello.com/c/P4Ckr0Cm/3008-cnt-fix-suseconnect-binary-location 
@wstephenson: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/43249/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged cb04bb3b65702d83e59e25455f9d2b01eae384c8 into 95101cb0e2067cf010b3527ca249fff225188000 )

**Comment by kalabiyau** [comment]
lgtm

**Comment by kalabiyau** [comment]
:ghost:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/43250/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged e6a04148ee518fc75633148f2cc9525379a3a6c4 into 95101cb0e2067cf010b3527ca249fff225188000 )

**Pull request merged**
