### PR TITLE
Add guard to Gemfile

### PR DESCRIPTION
**Pull request by felixsch**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98577/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 1f49f290eb3dca1283001993811fe699532aa6de into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98584/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged f3ba221212330040ca00bb84b932d857b39f9cd5 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98586/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged f3ba221212330040ca00bb84b932d857b39f9cd5 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98618/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged f3ba221212330040ca00bb84b932d857b39f9cd5 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98820/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged f3ba221212330040ca00bb84b932d857b39f9cd5 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100021/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a8d0ca6d2d4fd9f2d35072e286520a9620b52c2e into a4c3130f742800fb49c70cea032ed1d38c1aa8c7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100022/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 239b766f3d924bd8aa1b9e939d82a6ab4729d6da into 6ba0fe0d1034c0dd25997a6824d4e63eecf46e41)

**Pull request merged**
