### PR TITLE
Check that the output of activating an extension is correct

### PR DESCRIPTION
**Pull request by lagartoflojo**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/97118/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle15sp0. (Merged 640ad7de72392b8f48ed1343c723457bbe1d6f53 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/97119/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 640ad7de72392b8f48ed1343c723457bbe1d6f53 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98591/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 640ad7de72392b8f48ed1343c723457bbe1d6f53 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/99741/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 5a4cfd31fbcab031fae7019564f91f68863f066c into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/99744/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged a5f418ef1eb3cf2cbe562ef8c35008f973961827 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100021/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a5f418ef1eb3cf2cbe562ef8c35008f973961827 into a4c3130f742800fb49c70cea032ed1d38c1aa8c7)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/100022/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged a5f418ef1eb3cf2cbe562ef8c35008f973961827 into 6ba0fe0d1034c0dd25997a6824d4e63eecf46e41)

**Pull request closed without merging**
