### PR TITLE
do not exit when zypper has 0 repositories configured 2865

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/12753/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 2c5d80796b9afa74a3497e525b62429794025a97 into 2bc9686b5640072256f143c51ee522c3d28243f7 )

**Comment by suse-tests-pass** [comment]
@wstephenson is your reviewer :dancers: check https://trello.com/c/pLDhYF62/2865-cnt-do-not-fail-when-zypper-has-empty-repo-list 
@wstephenson: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/12755/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged cfc2e7ae6c5a63364ef1322373661dcb949f4f53 into 2bc9686b5640072256f143c51ee522c3d28243f7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/12764/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged a0d67da4bdb65717384060b3f13ab02db99667b9 into 2bc9686b5640072256f143c51ee522c3d28243f7 )

**Comment by wstephenson** [comment]
LGTM

**Pull request merged**
