### PR TITLE
Add awk package to SLE15 dockerfile

### PR DESCRIPTION
**Pull request by thutterer**
Seems to be required for building the native extension for 'ffi' gem.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/98594/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged d89d71b2e04621dfea866286c8d4a57814582a3a into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100021/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d89d71b2e04621dfea866286c8d4a57814582a3a into a4c3130f742800fb49c70cea032ed1d38c1aa8c7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100022/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 6d745f19e3509fce33721d6ccbe21ce5f09fb294 into 6ba0fe0d1034c0dd25997a6824d4e63eecf46e41)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100023/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a9889c7f995f3e533e8db24be9054952e66f724e into e60c1b0714cd2061474ee95f3683de3963dbe2e3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100497/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a9889c7f995f3e533e8db24be9054952e66f724e into 7bc15daae786fa4f3e11dd7edc5598ee566c66e8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100584/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged db01d2902b15edd16981aa5694b066d6110526fc into 7bc15daae786fa4f3e11dd7edc5598ee566c66e8)

**Pull request merged**
