### PR TITLE
install release package with --no-recommends and with "-t product" 2847

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/9446/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged de5ae2bd39118d5c42c65f0ecddc051346041243 into 0fb12b4a70f20466cf577540d5cacc317e7d69c2 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/9706/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged de5ae2bd39118d5c42c65f0ecddc051346041243 into 0fb12b4a70f20466cf577540d5cacc317e7d69c2 )

**Comment by suse-tests-pass** [comment]
@lagartoflojo is your reviewer :dancers: check https://trello.com/c/7tN4NMgF/2847-migration-api-allow-downgrade-of-extension-products-in-any-order 
@lagartoflojo: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by lagartoflojo** [comment]
LGTM, but why is it needed?

**Pull request merged**
