### PR TITLE
Set uuid to nil in case dmidecode fails / Card 2837

### PR DESCRIPTION
**Pull request by lagartoflojo**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@nadjaw is your reviewer :dancers: check https://trello.com/c/aUHxGuyg/2837-cnt-systems-without-uuid-should-be-able-to-register 
@nadjaw: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/5965/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged c0c795749864360f84684b937a3484012499ddfa into 7f871052dd4983aa3252b1f42e4a9a7e7138ca22 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/5974/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged cd92c676f88eb3b4f842538c1f288a41b7600f86 into 7f871052dd4983aa3252b1f42e4a9a7e7138ca22 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/5993/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 19a4e195d70e94766818819212993efded5df27f into 7f871052dd4983aa3252b1f42e4a9a7e7138ca22 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/5997/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 4a3eb34c1d1721d213601a54462ebb51e652044b into 7f871052dd4983aa3252b1f42e4a9a7e7138ca22 )

**Comment by digitaltom** [comment]
LGTM

**Pull request merged**
