### PR TITLE
Remove an extra API call, refactor a little bit 4409

### PR DESCRIPTION
**Pull request by ikapelyukhin**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@lagartoflojo will review your pull request :dancers: check https://trello.com/c/UC40AXI7/4409-suseconnect-list-extensions-extra-api-call
  @lagartoflojo: Please review this pull request using our guidelines:
  * test for acceptance criteria / functionality
  * check if the new code is covered with tests
  * check for unintended consequences
  * encourage usage of the boyscout rule
  * make sure the code is architected in the best way
  * check that no unnecessary technical debt got introduced
  * make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-pass** [comment]
@lagartoflojo will review your pull request :dancers: check https://trello.com/c/UC40AXI7/4409-suseconnect-list-extensions-extra-api-call
  @lagartoflojo: Please review this pull request using our guidelines:
  * test for acceptance criteria / functionality
  * check if the new code is covered with tests
  * check for unintended consequences
  * encourage usage of the boyscout rule
  * make sure the code is architected in the best way
  * check that no unnecessary technical debt got introduced
  * make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21869/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged a6b1e1591feaec76b61434d039275c164dbdc7ac into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by ikapelyukhin** [comment]
Rebased this PR on top of `auto-agree-with-product-licenses` branch.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21888/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 9521df656f65c5de1b038826b9a234e69d1348f0 into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23579/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 9521df656f65c5de1b038826b9a234e69d1348f0 into 09072bd4546b441f627c7274c980b8333597b5e6 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23813/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 9521df656f65c5de1b038826b9a234e69d1348f0 into 09072bd4546b441f627c7274c980b8333597b5e6 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-Connect-Prophet/23818/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged a2efc00d0798c04d49de030011c6189fb4490090 into 09072bd4546b441f627c7274c980b8333597b5e6 )

**Comment by digitaltom** [comment]
Good improvement 👍

**Pull request merged**
