### PR TITLE
Add --list-extensions option that lists all available extensions / Card 2784

### PR DESCRIPTION
**Pull request by lagartoflojo**

### CODE REVIEW

**Comment by NadjaW** [comment]
lgtm

**Comment by suse-tests-pass** [comment]
@kalabiyau is your reviewer :dancers: check https://trello.com/c/aFwTO77X/2784-5-cnt-allow-suse-connect-to-list-available-extensions 
@kalabiyau: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by kirushik** [comment]
@lagartoflojo @kalabiyau Why haven't we merged this yet?

**Comment by lagartoflojo** [comment]
@kirushik I'm adding one last thing about skipping products that have "available: false" (SMT case)

**Comment by kirushik** [comment]
OK, I see.

**Comment by lagartoflojo** [comment]
@kalabiyau Added. Could you review please?

**Comment by lagartoflojo** [comment]
@kirushik Added. Could you review it please?

**Comment by kirushik** [comment]
LGTM, both latest commit and PR as a whole.

**Comment by lagartoflojo** [comment]
Cool thx :)

**Pull request merged**
