### PR TITLE
test

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/144820/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b9c0ec8ea666834c995af6bcfa75ef568b4f4b7a into 71e280d48d0d939a45dc8bf08cf7842138d0f36a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/144823/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-build-image-sle12sp3. (Merged b9c0ec8ea666834c995af6bcfa75ef568b4f4b7a into 71e280d48d0d939a45dc8bf08cf7842138d0f36a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/144829/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b9c0ec8ea666834c995af6bcfa75ef568b4f4b7a into 71e280d48d0d939a45dc8bf08cf7842138d0f36a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/144979/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b9c0ec8ea666834c995af6bcfa75ef568b4f4b7a into 7817706a1926465125f7b3a9ec43bf9fc9483ec2)

**Pull request closed without merging**
