### PR TITLE
Output proper message when SUSEConnect is called without parameters (and other small improvements)

### PR DESCRIPTION
**Pull request by fschueller**
https://trello.com/c/mhjrovKR/517-scpcnt-output-proper-message-when-suseconnect-is-called-without-parameters-and-other-small-improvements

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/156554/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 97020319a0340dcb55b61257b5aa16da4566d159 into d0bbc6697c51d103e4bfd120df7fd1f5f9741f15)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/156600/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 431dbde1cec890c743787a0471dc8ebd3584f24d into d0bbc6697c51d103e4bfd120df7fd1f5f9741f15)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/156601/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b3bc635307ca2c943cdd210d7dc24b8c842ef340 into d0bbc6697c51d103e4bfd120df7fd1f5f9741f15)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/156639/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 05b6e124d6e54698a3b3afccd88adf5eb8f4f7aa into d0bbc6697c51d103e4bfd120df7fd1f5f9741f15)

**Comment by thutterer** [comment]
I agree with @tmuntaner:

- Either print what `--help` would print.
- Or print no options at all, and only refer to `--help`. Showing a subset of options is really a bit confusing and only opens room for discussion what a "common" option is.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/156884/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 84b43acac02aedd64f14e9fc3f6d4c3a3b32f29c into d0bbc6697c51d103e4bfd120df7fd1f5f9741f15)

**Pull request merged**
