### PR TITLE
Revert changes of rake build removal

### PR DESCRIPTION
**Pull request by tmuntan1**
Jenkins needs rake build during integration testing

### CODE REVIEW

**Comment by lagartoflojo** [comment]
The new [package.rake](https://github.com/SUSE/connect/blob/master/lib/tasks/package.rake) does many of these things, it seems to just be missing the `osc build` command. Could we add that as a new task in `package.rake` and modify the Jenkinsfiles accordingly?

Also: `README.md` still mentions `rake build`.

**Comment by lagartoflojo** [comment]
(not a formal review -- just a comment... I don't have capacity to review further right now :cry: )

**Comment by tmuntan1** [comment]
ok, I will look into it

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/91230/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged de4f92b04ed8a8316a74ef980de4bb9ccc1f85d0 into df69e68dcf6abee93b4953291ce3bfac326339f0 )

**Comment by tmuntan1** [comment]
Updated: added `osc build` with calls to the package rake task in the docker integration tests.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/91236/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged f43243e474dd067d8977fa961f4fe3e4560a53c6 into df69e68dcf6abee93b4953291ce3bfac326339f0 )

**Comment by tmuntan1** [comment]
@fschueller  thanks

**Pull request merged**
