### PR TITLE
do not build on i586 and s390

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/97365/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 727e0177a4534780cb639fcf1e616cee4f4300a7 into e209bca882be92493fef93e7370589a8dccbf7bd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100021/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 727e0177a4534780cb639fcf1e616cee4f4300a7 into a4c3130f742800fb49c70cea032ed1d38c1aa8c7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100022/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 727e0177a4534780cb639fcf1e616cee4f4300a7 into 6ba0fe0d1034c0dd25997a6824d4e63eecf46e41)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100023/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 727e0177a4534780cb639fcf1e616cee4f4300a7 into e60c1b0714cd2061474ee95f3683de3963dbe2e3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/100362/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 776d6cae0fbb0637ade0030ff291f59c3de74196 into e60c1b0714cd2061474ee95f3683de3963dbe2e3)

**Pull request merged**
