### PR TITLE
Add SLE_15_SP3 to integration tests

### PR DESCRIPTION
**Pull request by JanZerebecki**
I'm not sure if that is what the environment should be.
Do you want to copy the container into the scc registry before merging this?

### CODE REVIEW

**Comment by digitaltom** [comment]
To add this to https://github.com/SUSE/connect/blob/master/Jenkinsfile I tried: 
`docker build -t connect.15sp3 -f Dockerfile.15sp3 .` 
and this fails with: 
```
'awk' not found in package names. Trying capabilities.
'libx86emu1' not found in package names. Trying capabilities.
'osc' not found in package names. Trying capabilities.
No provider of 'libx86emu1' found.
No provider of 'osc' found.
```

**Comment by digitaltom** [comment]
The Dockerfile is fixed now.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 76156d5e9862ea1941700e1a00a5eb909a36a58e into d04d7ce80ade1911c02909b5e128c3cc2a8404b6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing. (Merged dffef3625213350b846e6c3b3ae60e9b9ee61537 into d04d7ce80ade1911c02909b5e128c3cc2a8404b6)

**Review by digitaltom — APPROVED** [review]

**Pull request merged**
