### PR TITLE
contribution by coolo: make SUSEConnect build on Ruby 2.6

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/180717/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 914889bfa9fac780d8de62f1171d88c6d1587801 into dea7800351eac1bf5b38b34ac81c87f388e977b1)

**Comment by digitaltom** [comment]
Depends on: https://trello.com/c/i2ZPrVAp/3043-fix-suseconnect-jenkins

**Comment by fschueller** [comment]
> Depends on: https://trello.com/c/i2ZPrVAp/3043-fix-suseconnect-jenkins

Possible fix: https://github.com/SUSE/connect/pull/410

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/180935/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 914889bfa9fac780d8de62f1171d88c6d1587801 into 7594b500bf113542d6a0d579ef10fe234f18aea3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/180966/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8f4b8b21e3314cf1284216b5bd60d95795540dee into 7594b500bf113542d6a0d579ef10fe234f18aea3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/181011/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 65462645461279eb85d01b42bc5ad2125f6524d7 into 2837aa261e78e46df513f9b825a7287b7eb99779)

**Pull request merged**
