### PR TITLE
adding rpmlintrc to skip known warnings

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/323082/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b31548faf9f60a3ac3840e70327f5831e5fad06 into 559ee54849d0b20e2491f4249c2bea9d6ab4a3ca)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/331688/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b31548faf9f60a3ac3840e70327f5831e5fad06 into 238561d1f1acb8b1fe27571d8177308231a01c60)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/339481/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b31548faf9f60a3ac3840e70327f5831e5fad06 into 1c8c9c6970fe13125411a658c2aab774df601df4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/341438/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b31548faf9f60a3ac3840e70327f5831e5fad06 into 0b5188d6067a2f75ae09c5a1d3880c224e7a693e)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/343478/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests-sle12sp3. (Merged 9b31548faf9f60a3ac3840e70327f5831e5fad06 into 6750c164e3c05b7f81ae7205b6918a64a1f39d45)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/343771/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b31548faf9f60a3ac3840e70327f5831e5fad06 into a4b6ed53bdc65b08afcd97fc4eceb1fef04a68a3)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
