### PR TITLE
Improving the error message in case the system is not registered.

### PR DESCRIPTION
**Pull request by digitaltom**
inspired by bsc#1174067

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/339484/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7d7f8b16c0f8da9cb8cfe7ccdc74ca456473c553 into 1c8c9c6970fe13125411a658c2aab774df601df4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/341438/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7d7f8b16c0f8da9cb8cfe7ccdc74ca456473c553 into 0b5188d6067a2f75ae09c5a1d3880c224e7a693e)

**Review by gionaufal — APPROVED** [review]
lgtm!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/343478/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7d7f8b16c0f8da9cb8cfe7ccdc74ca456473c553 into 6750c164e3c05b7f81ae7205b6918a64a1f39d45)

**Pull request merged**
