### PR TITLE
Bash script for OEM now is an example

### PR DESCRIPTION
**Pull request by kalabiyau**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/79565/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged bb76d0738aad29a3a23199fb50970b266fd52775 into 9024d7668c5eab5656996a4cd74e76c55494fb50 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/82163/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged bb76d0738aad29a3a23199fb50970b266fd52775 into 1636b008decb941963956bc2829be42b90afb5dd )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/82187/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged bb76d0738aad29a3a23199fb50970b266fd52775 into 7c8572c3d39a98076d69f4fd03eac9a84c8b73be )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/82419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged bb76d0738aad29a3a23199fb50970b266fd52775 into 3c44899731ecf152256d7e10a159ea8fe4b7d765 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/84027/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged bb76d0738aad29a3a23199fb50970b266fd52775 into 07f35bdaecaeda596aa19bc7d9123de856c21feb )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/84352/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1505f9aba16a566647722d584486fadbec50fa28 into 4974b9a9fbc4eaf0d995cb47c723c5792dc10248 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/84354/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 1505f9aba16a566647722d584486fadbec50fa28 into 4974b9a9fbc4eaf0d995cb47c723c5792dc10248 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/84358/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 67334afc45d0dbac361498c1699b0bbe78d389d1 into 4974b9a9fbc4eaf0d995cb47c723c5792dc10248 )

**Pull request merged**
