### PR TITLE
output stderr + stdout of system commands in debug mode

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/92756/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 833932564aa5717cc0ab67e203e5b7b5f425e44d into 187a0486a7cefdbb7c6fb4e9dac33a351359e6da )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/106917/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 833932564aa5717cc0ab67e203e5b7b5f425e44d into cfc108096608c9ec942f196b3a32ccf470b81931 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/116107/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 1eee711ffb33f7df285da941039d7f229da4599c into cfc108096608c9ec942f196b3a32ccf470b81931 )

**Comment by thutterer** [comment]
LGTM

**Pull request merged**
