### PR TITLE
Add a Dockerfile for SLES 12 SP2 / Card 3383

### PR DESCRIPTION
**Pull request by lagartoflojo**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@kalabiyau is your reviewer :dancers: check https://trello.com/c/bau6lDNj/3383-cloud-7-beta-program 
@kalabiyau: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by lagartoflojo** [comment]
The regcodes that end up in `/root/.regcodes` don't work at the time of writing, but they should as soon as officially SP2 is released.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/117010/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 967a8e33f6682decd45490c255cfdcf0264e5bf4 into cfc108096608c9ec942f196b3a32ccf470b81931 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/SCC-Connect-Prophet/117024/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 967a8e33f6682decd45490c255cfdcf0264e5bf4 into ca89824e9e925363c9a90a3039e270a1f0623e2f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/117028/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 967a8e33f6682decd45490c255cfdcf0264e5bf4 into ca89824e9e925363c9a90a3039e270a1f0623e2f )

**Comment by kalabiyau** [comment]
LGTM - all is green, working as expected

**Pull request merged**
