### PR TITLE
proofreading fixes]

### PR DESCRIPTION
**Pull request by wstephenson**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/149589/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a5de0d2bd16de97261e375b3e5453d19bf58c782 into ab7da3fff8245b35f00c88983a0fa0a1daa48426)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/149590/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d21b8ebf66df57befa407ae570d13a3648276275 into ab7da3fff8245b35f00c88983a0fa0a1daa48426)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/149600/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d21b8ebf66df57befa407ae570d13a3648276275 into 7aeceb6d09bf05cf7eaa136e9db890de081bb797)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/150717/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b0f1dc8fd68c7c4d22ee06f947a2e0bf9c06c8d into 81a689184229ea32b748289aa93defeca357ec1f)

**Comment by lagartoflojo** [comment]
@wstephenson I approved this btw

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/151283/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b0f1dc8fd68c7c4d22ee06f947a2e0bf9c06c8d into 6ce9913d1663e90aa12c272672583821415f6c82)

**Comment by wstephenson** [comment]
I keep updating the branch and then forgetting to check it and merge it before HEAD moves forwards again...

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/151288/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f754b873bdc6ae051ad9261e514754b83db0d15b into 6ce9913d1663e90aa12c272672583821415f6c82)

**Pull request merged**
