### PR TITLE
[Review] Request from 'digitaltom' @ 'SUSE/connect/review_150928_add_integration_tests_for_migration_rollback'

### PR DESCRIPTION
**Pull request by digitaltom**
Please review the following changes:
  * 26299ad first test for migration / rollback library calls
  * ef94960 divide tests to different features
  * 85e72b3 Merge pull request #238 from SUSE/fix-requires
  * 7912101 Use Conflicts instead of Required for yast2-registration
  * 75fffde Merge pull request #237 from SUSE/update-readme
  * 021e185 Update README.md
  * 64920cd Show how to submit a maintenance request

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step bundle.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-build-image.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 8d4d949660675ca6988de419ec74b18598d6b468 into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 15aadb75a4e115a1d9a3874c9ba5f4607771b81f into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/9/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 15aadb75a4e115a1d9a3874c9ba5f4607771b81f into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/34/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged a22ae93220facfde54858db8145da5414fc2037f into e74cdcdbc8b3bd4736d23f7c9c3962b670f9f4f7 )

**Comment by kirushik** [comment]
Perfect, just perfect.

LGTM.

**Pull request merged**
