### PR TITLE
Add YaST.list_installer_updates to enable YaST installer auto-update / Card 3360

### PR DESCRIPTION
**Pull request by lagartoflojo**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/SCC-Connect-Prophet/106376/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 79d5fac4652ad27a48c0abf89fd94ce908b0fd9a into 187a0486a7cefdbb7c6fb4e9dac33a351359e6da )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/106377/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged fca83a455f5b7f03e6206ce74365c763a921c6e4 into 187a0486a7cefdbb7c6fb4e9dac33a351359e6da )

**Comment by wstephenson** [comment]
ls it worth adding a test that it returns an empty array in the case of no installer updates on the repo?

Otherwise LGTM

**Comment by lagartoflojo** [comment]
@wstephenson how's this? https://github.com/SUSE/connect/pull/268/commits/ea8112aae6a9b3c179f4df5a66645db503848d8a

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/106407/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged ea8112aae6a9b3c179f4df5a66645db503848d8a into 187a0486a7cefdbb7c6fb4e9dac33a351359e6da )

**Comment by wstephenson** [comment]
lvgtm

**Comment by lagartoflojo** [comment]
@wstephenson one small addendum to review please :)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/SCC-Connect-Prophet/106414/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged c2afef53f5e2cfc42969494ffd4db5c2fc0f5003 into 187a0486a7cefdbb7c6fb4e9dac33a351359e6da )

**Comment by wstephenson** [comment]
lgtm

**Pull request merged**
