### PR TITLE
Travis is no longer working with ruby 2.1.2, use 2.1 instead

### PR DESCRIPTION
**Pull request by tmuntaner**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/229868/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 612da9eda5a3819cd0f25ac62579bb6366965d66 into 5da3f9a7c4ee11c4bf5273a2374cbd12ac21a961)

**Comment by thutterer** [comment]
I think this broke because of Ubuntu 16.04 being the new default: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

And according to http://rubies.travis-ci.org/ 16.04 doesn't come with Ruby 2.1.2, neither does it come with 2.1 @tmuntaner 
The only 2.1.x release I see in that list is 2.1.9 ... maybe we should set that? Or explicitly use Ubuntu 14.04 like described in the article above?

What do you think is better?

**Comment by tmuntaner** [comment]
@thutterer Thanks, I use rbenv myself and wasn't familiar with the binary process of rvm. You're right, https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ only shows `2.1.5` and `2.1.9`.

Do you have any issue with just selecting ruby `2.1` and letting rvm grab the latest available ruby 2.1 version? On ubuntu 16.04, it will automatically select `2.1.9`, which is what we want. If travis defaults to a new ubuntu and only has `2.1.10`, we will run into the same issue again.

I don't see the benefit of using an EOL ubuntu os as the base of our tests when the latest version works with `2.1.9` (the version currently used in SLE 12 SP5). I also don't really want to keep my eye on ubuntu releases and what binaries rvm releases for them, so I'm fine with the default ruby 2.1 version.

Thoughts?

**Comment by thutterer** [comment]
@tmuntaner Perfect! :+1:

**Pull request merged**
