### PR TITLE
[Review] Request from 'digitaltom' @ 'SUSE/connect/review_151023_rollback_feature'

### PR DESCRIPTION
**Pull request by digitaltom**
Please review the following changes:
  * 43ee768 finalize tests for rollback
  * 090ee48 Merge branch 'master' into review_151023_rollback_feature
  * c3864d8 Undone rollback feature for Connect

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/9862/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 43ee7683ba01f6f53705540667216d7c1e210f4b into 7c585283335c3f72bd81f0a6126492d069a944a1 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/9863/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged dc87ba2470704f3ffda9fd73b030b9db603a13cc into 7c585283335c3f72bd81f0a6126492d069a944a1 )

**Comment by lagartoflojo** [comment]
Tested with docker, LGTM

**Comment by digitaltom** [comment]
\o/

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/9866/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 6eee5143a38f83800fd82d9ab41e893fb42aea70 into 7c585283335c3f72bd81f0a6126492d069a944a1 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/9868/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 8e18a3f1d86af532d0b6fc806425d9ffb6fd04f9 into 7c585283335c3f72bd81f0a6126492d069a944a1 )

**Pull request merged**
