### PR TITLE
change text from "SCC returned..." to "Registration server returned..."

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/SCC-Connect-Prophet/55903/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 7a3681908cd8b07a681019ce839d3a31a3880d70 into 95eee71d1e246e46f11b6314436ff97215cbce5f )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/55913/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged c0e8a5c560f013182abc5326c92642f5cdf9508e into 656e21f4ff6620dadbd6ef3af6a5e1919e0fb66d )

**Comment by thutterer** [comment]
I'll approve as soon as you have merged latest changes from `master` into this branch :wink:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/56474/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged d6c4f8c42c4e41f947a0e1186660a13eaa35e87d into 656e21f4ff6620dadbd6ef3af6a5e1919e0fb66d )

**Comment by digitaltom** [comment]
@thutterer ping

**Pull request merged**
