### PR TITLE
Ignore lscpu lines with no value 2883

### PR DESCRIPTION
**Pull request by kirushik**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@kalabiyau is your reviewer :dancers: check https://trello.com/c/JS2nJFth/2883-cnt-suseconnect-fails-when-lscpu-returns-empty-values 
@kalabiyau: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by kalabiyau** [comment]
Looks totally good

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/18468/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged fe1d910bbd44a333623531796211be3e3faf027b into ffdb7af187525fc9ca6f26f058884221b985ff15 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/18474/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged e58bed3ab1729528285adaee109c4118d1d9cde9 into ffdb7af187525fc9ca6f26f058884221b985ff15 )

**Pull request merged**
