### PR TITLE
Update to version 0.2.27

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/9878/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged a71c033d09b80739671e29cbc8a205f670237796 into 2bc9686b5640072256f143c51ee522c3d28243f7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/11217/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged d656d83911e7ddc25f36be9840788808f5a0872c into 2bc9686b5640072256f143c51ee522c3d28243f7 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/13160/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged d656d83911e7ddc25f36be9840788808f5a0872c into 582941ca2598d4e5604c53c4bde72aa10cf48d8e )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/13161/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged c608cbb8939179523c50828bc85dcae57618c02e into 582941ca2598d4e5604c53c4bde72aa10cf48d8e )

**Comment by kirushik** [comment]
ДПЕЬ

**Pull request merged**
