### PR TITLE
update error message about product identifiers 3695

### PR DESCRIPTION
**Pull request by thutterer**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@kalabiyau will review your pull request :dancers: check https://trello.com/c/nogSvBtL/3695-connect-fix-message-about-where-to-find-product-identifiers
  @kalabiyau: Please review this pull request using our guidelines:
  * test for acceptance criteria / functionality
  * check if the new code is covered with tests
  * check for unintended consequences
  * encourage usage of the boyscout rule
  * make sure the code is architected in the best way
  * check that no unnecessary technical debt got introduced
  * make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-Connect-Prophet/2766/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged e61f1da7c9acdde98c98c8b16eb2d3c710ba48c7 into 4b2a4b89f729d9accfeb2d998581b0e64744254f )

**Comment by kalabiyau** [comment]
@thutterer we probably would need a submission to IBS then?

**Comment by thutterer** [comment]
> we probably would need a submission to IBS then?

Yes, will do a version bump and SR (and updates to PACKAGE.md) in a separate PR.

**Pull request merged**
