### PR TITLE
Auto agree with product licenses 4392

### PR DESCRIPTION
**Pull request by thutterer**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@digitaltom will review your pull request :dancers: check https://trello.com/c/hpFr3Y35/4392-suseconnect-needs-to-call-zypper-with-auto-agree-with-product-licenses
  @digitaltom: Please review this pull request using our guidelines:
  * test for acceptance criteria / functionality
  * check if the new code is covered with tests
  * check for unintended consequences
  * encourage usage of the boyscout rule
  * make sure the code is architected in the best way
  * check that no unnecessary technical debt got introduced
  * make sure that no unnecessary FIXMEs or TODOs got added

**Comment by mlandres** [comment]
@digitaltom Yes, only commands that will install packages (in,up,patch,dup) may ask for licenses. addervice or refs won't.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21828/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 560f6a5080ef53cb4cbac1c14d80ef5dd66b4ef5 into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21835/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 197c3c411f954936ad5a70feb0dd1d4baaf34c3b into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21838/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 9034ac9a4c8b5bf10cf48ff7c32d03ba511325cf into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21871/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 261cf2d6c8f52dcd9658edfeffb49d51232cee43 into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/21875/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1775f63b04b9288edf0fe781901243b004e0da07 into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23579/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1775f63b04b9288edf0fe781901243b004e0da07 into 09072bd4546b441f627c7274c980b8333597b5e6 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23605/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1775f63b04b9288edf0fe781901243b004e0da07 into 09072bd4546b441f627c7274c980b8333597b5e6 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23824/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1775f63b04b9288edf0fe781901243b004e0da07 into b36c1e54cdeaa121c58929f1097d7f4e446b091d )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23828/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1b5a54279a4c4bb2a7161b68af018ee4d5caa833 into b36c1e54cdeaa121c58929f1097d7f4e446b091d )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/24152/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1b5a54279a4c4bb2a7161b68af018ee4d5caa833 into 1d32a31ced1a47f21a768e222ed24f1386c9b2b4 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/24641/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 1b5a54279a4c4bb2a7161b68af018ee4d5caa833 into 1d32a31ced1a47f21a768e222ed24f1386c9b2b4 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-Connect-Prophet/24654/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 1b5a54279a4c4bb2a7161b68af018ee4d5caa833 into dee6a7d6b9465dbf0d965804a55bb61b026fed26 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-Connect-Prophet/24656/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged bd6522991212c72b364d26f4047ea2329fd22316 into dee6a7d6b9465dbf0d965804a55bb61b026fed26 )

**Pull request merged**
