### PR TITLE
- Do not let zypper attempt to read products from remote locations

### PR DESCRIPTION
**Pull request by rjschwei**
when we are only interested in the products installed locally.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/58062/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 19be79992553598904396122f52c8d946e3e8493 into ca91fc0e40ffe330aaf6b66da1362a5e5842b544 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/58076/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 19af16e21741538d6057ade92faf1ff41757ac66 into ca91fc0e40ffe330aaf6b66da1362a5e5842b544 )

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/58085/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged 60d46c9522bb32bca080be1e8b84bfaab63b7cf5 into ca91fc0e40ffe330aaf6b66da1362a5e5842b544 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/58090/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged bae570192498c56e76b38fc7451ccbf6dd06f6bf into ca91fc0e40ffe330aaf6b66da1362a5e5842b544 )

**Comment by digitaltom** [comment]
Thank you for the patch!

**Pull request merged**
