### PR TITLE
replace env ruby with native path

### PR DESCRIPTION
**Pull request by Zennoe**
builds in home branch on OBS succeeded.

Addresses a packaging guideline.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/362502/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a927536aa155c15048cd62726904b6fc6e294a2a into ff798ab7c91f82cd0e2c9537d06155232c5571a8)

**Comment by felixsch** [comment]
Good job! Since we want to release the changes, can bump the version (patch) and add a changelog entry. Is there a bug open for this problem? If yes, make sure to reference it from your changelog entry.

**Comment by Zennoe** [comment]
> Since we want to release the changes, can bump the version (patch) and add a changelog entry.
Sure. Will do.
>  Is there a bug open for this problem?
Good question

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/SCC-Connect-Prophet/362772/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 41c18050d0e162b2e9958ce855e4fc99db1524ae into ff798ab7c91f82cd0e2c9537d06155232c5571a8)

**Review by felixsch — APPROVED** [review]
lgtm :+1:

**Pull request merged**
