### PR TITLE
add --no-refresh to find_products and install_release_package methods_2836

### PR DESCRIPTION
**Pull request by vlewin**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@nadjaw is your reviewer :dancers: check https://trello.com/c/iuAs0tnu/2836-1-connect-add-no-refresh-to-find-products-and-install-release-package-methods 
@nadjaw: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
http://river.suse.de/job/scc-connect-prophet/6340/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged f35044ab89f56df453d9a7a8cd9925489bc9f326 into 7f6293ba706929f22f5eb60ef30a9363305d3777 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/6343/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 085d36bd7ddbdbe707a45f14d97a36c802ec4d8d into 7f6293ba706929f22f5eb60ef30a9363305d3777 )

**Comment by NadjaW** [comment]
lgtm

**Pull request merged**
