### PR TITLE
This tiny quirk stopped Jenkins from succeeding 4421

### PR DESCRIPTION
**Pull request by kirushik**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
@fschueller will review your pull request :dancers: check https://trello.com/c/4Lk4Tled/4421-scc-connect-build-are-broken
  @fschueller: Please review this pull request using our guidelines:
  * test for acceptance criteria / functionality
  * check if the new code is covered with tests
  * check for unintended consequences
  * encourage usage of the boyscout rule
  * make sure the code is architected in the best way
  * check that no unnecessary technical debt got introduced
  * make sure that no unnecessary FIXMEs or TODOs got added

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-Connect-Prophet/23558/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project connect on step docker-run-tests.
( Failure: Merged a61714e5aef4978c1845faaa8e1c4a5843f96699 into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Comment by thutterer** [comment]
@kirushik Instead of your last commit (https://github.com/SUSE/connect/pull/301/commits/0031f76f143c970ba745ec6164e1e2c56f1b44d6), can you please cherry-pick https://github.com/SUSE/connect/pull/298/commits/9034ac9a4c8b5bf10cf48ff7c32d03ba511325cf from my open PR branch. Contents are the same and makes my merge probably easier later on.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-Connect-Prophet/23561/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 0031f76f143c970ba745ec6164e1e2c56f1b44d6 into 0402cc599123c8cb5d94c474e96d65caa051b8d4 )

**Pull request merged**
