### PR TITLE
[Review] Request from 'digitaltom' @ 'SUSE/connect/review_151216_prepare_submission_of_maintenance_update_for_sp1' 2920

### PR DESCRIPTION
**Pull request by digitaltom**
Please review the following changes:
  * 1573257 prepare submission of maintenance update for SP1
  * a0f7f6a v0.2.32

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/35762/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 1573257deb90f42c2dd4960cc37730900dce6444 into 3b983b51d592eb0d5b55e41a83d178194bb84542 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/35763/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged 2dcd047683f1bc66b3bc7154e8328a832bbd2e6b into 3b983b51d592eb0d5b55e41a83d178194bb84542 )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
http://river.suse.de/job/scc-connect-prophet/36074/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
( Success: Merged a86da615b4782fb8697b659a2bbe8e93747de485 into 3b983b51d592eb0d5b55e41a83d178194bb84542 )

**Comment by suse-tests-pass** [comment]
@wstephenson is your reviewer :dancers: check https://trello.com/c/EfiBDAkT/2920-cnt-submit-current-connect-package-to-sp1-update 
@wstephenson: Please review this pull request using our guidelines: 
* test for acceptance criteria / functionality 
* check if the new code is covered with tests 
* check for unintended consequences 
* encourage usage of the boyscout rule 
* make sure the code is architected in the best way 
* check that no unnecessary technical debt got introduced 
* make sure that no unnecessary FIXMEs or TODOs got added

**Comment by wstephenson** [comment]
lgtm

tested on sp1, registration still works, and no warning on upgrade any more

**Pull request merged**
